# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: episode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='episode.proto',
  package='rl_trainer',
  syntax='proto3',
  serialized_pb=_b('\n\repisode.proto\x12\nrl_trainer\"p\n\x0f\x45xperienceTuple\x12\x0f\n\x07state_1\x18\x01 \x03(\x01\x12\x0e\n\x06\x61\x63tion\x18\x02 \x03(\x01\x12\x0e\n\x06reward\x18\x03 \x01(\x01\x12\x0f\n\x07state_2\x18\x04 \x03(\x01\x12\x1b\n\x13state_2_is_terminal\x18\x05 \x01(\x08\"A\n\x07\x45pisode\x12\x36\n\x11\x65xperience_tuples\x18\x01 \x03(\x0b\x32\x1b.rl_trainer.ExperienceTupleb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EXPERIENCETUPLE = _descriptor.Descriptor(
  name='ExperienceTuple',
  full_name='rl_trainer.ExperienceTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_1', full_name='rl_trainer.ExperienceTuple.state_1', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='rl_trainer.ExperienceTuple.action', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='rl_trainer.ExperienceTuple.reward', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_2', full_name='rl_trainer.ExperienceTuple.state_2', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_2_is_terminal', full_name='rl_trainer.ExperienceTuple.state_2_is_terminal', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=141,
)


_EPISODE = _descriptor.Descriptor(
  name='Episode',
  full_name='rl_trainer.Episode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='experience_tuples', full_name='rl_trainer.Episode.experience_tuples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=208,
)

_EPISODE.fields_by_name['experience_tuples'].message_type = _EXPERIENCETUPLE
DESCRIPTOR.message_types_by_name['ExperienceTuple'] = _EXPERIENCETUPLE
DESCRIPTOR.message_types_by_name['Episode'] = _EPISODE

ExperienceTuple = _reflection.GeneratedProtocolMessageType('ExperienceTuple', (_message.Message,), dict(
  DESCRIPTOR = _EXPERIENCETUPLE,
  __module__ = 'episode_pb2'
  # @@protoc_insertion_point(class_scope:rl_trainer.ExperienceTuple)
  ))
_sym_db.RegisterMessage(ExperienceTuple)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), dict(
  DESCRIPTOR = _EPISODE,
  __module__ = 'episode_pb2'
  # @@protoc_insertion_point(class_scope:rl_trainer.Episode)
  ))
_sym_db.RegisterMessage(Episode)


# @@protoc_insertion_point(module_scope)
